# Generated by Django 5.1.1 on 2024-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-status", "-created_time")},
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="to_do_management.tag"
            ),
        ),
    ]
